export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const CHANGE_USP = 'CHANGE_USP';
export const CHANGE_STARTUPDESC = 'CHANGE_STARTUPDESC';
export const CHANGE_DESIGN = 'CHANGE_DESIGN';
export const CHANGE_INDUSTRY = 'CHANGE_INDUSTRY';


